Questionnaires.Web/Models/Answer.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Questionnaires.Web.Models
{
    public class Answer
    {
        public int Id { get; set; }

        [Required]
        public string SessionId { get; set; }

        [Required]
        public int QuestionId { get; set; }

        public Question Question { get; set; }

        [Required]
        public int ChoiceId { get; set; }

        public Choice Choice { get; set; }
    }
}

Questionnaires.Web/Models/Questionnaire.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Questionnaires.Web.Models
{
    public class Questionnaire
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        public List<Question> Questions { get; set; }
    }
}

Questionnaires.Web/Controllers/Api/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Questionnaires.Web.Models;

namespace Questionnaires.Web.Controllers.Api
{
    public class QuestionnaireController : ApiController
    {
        private QuestionnaireContext db = new QuestionnaireContext();

        // GET api/Questionnaire
        public IEnumerable<Questionnaire> GetQuestionnaires()
        {
            return db.Questionnaires.AsEnumerable();
        }

        // GET api/Questionnaire/5
        public Questionnaire GetQuestionnaire(int id)
        {
            Questionnaire questionnaire = db.Questionnaires
                .Include("Questions")
                .SingleOrDefault(x => x.Id == id);
            if (questionnaire == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return new Questionnaire
                {
                    Id = questionnaire.Id,
                    Title = questionnaire.Title,
                    Questions = questionnaire.Questions.Select(x => new Question
                        {
                            Id = x.Id,
                            Text = x.Text,
                            QuestionnaireId = x.QuestionnaireId
                        }).ToList()
                };
        }

        // PUT api/Questionnaire/5
        public HttpResponseMessage PutQuestionnaire(int id, Questionnaire questionnaire)
        {
            if (!ModelState.IsValid)
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }

            if (id != questionnaire.Id)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }

            db.Entry(questionnaire).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                return Request.CreateErrorResponse(HttpStatusCode.NotFound, ex);
            }

            return Request.CreateResponse(HttpStatusCode.OK);
        }

        // POST api/Questionnaire
        public HttpResponseMessage PostQuestionnaire(Questionnaire questionnaire)
        {
            if (ModelState.IsValid)
            {
                db.Questionnaires.Add(questionnaire);
                db.SaveChanges();

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.Created, questionnaire);
                response.Headers.Location = new Uri(Url.Link("DefaultApi", new { id = questionnaire.Id }));
                return response;
            }
            else
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }
        }

        // DELETE api/Questionnaire/5
        public HttpResponseMessage DeleteQuestionnaire(int id)
        {
            Questionnaire questionnaire = db.Questionnaires.Find(id);
            if (questionnaire == null)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            db.Questionnaires.Remove(questionnaire);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                return Request.CreateErrorResponse(HttpStatusCode.NotFound, ex);
            }

            return Request.CreateResponse(HttpStatusCode.OK, questionnaire);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Questionnaires.Web/Controllers/QuestionController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Questionnaires.Web.Models;

namespace Questionnaires.Web.Controllers
{
    public class QuestionController : Controller
    {
        private readonly QuestionnaireContext db = new QuestionnaireContext();

        //
        // GET: /Question/Details/5

        public ActionResult Details(int id = 0)
        {
            Question question = db.Questions
                                  .Include(x => x.Questionnaire)
                                  .Include(x => x.Choices)
                                  .SingleOrDefault(x => x.Id == id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // GET: /Question/Create

        public ActionResult Create(int questionnaireId)
        {
            return View(new Question {QuestionnaireId = questionnaireId});
        }

        //
        // POST: /Question/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Details", new {id = question.Id});
            }

            return View(question);
        }

        //
        // GET: /Question/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Question/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new {question.Id});
            }
            return View(question);
        }

        //
        // GET: /Question/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Question/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Details", "Questionnaire", new {id = question.QuestionnaireId});
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Questionnaires.Web/Controllers/QuestionnaireController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Questionnaires.Web.Models;

namespace Questionnaires.Web.Controllers
{
    public class QuestionnaireController : Controller
    {
        private readonly QuestionnaireContext db = new QuestionnaireContext();

        //
        // GET: /Questionnaire/

        public ActionResult Index()
        {
            return View(db.Questionnaires.ToList());
        }

        //
        // GET: /Questionnaire/Backbone

        public ActionResult Backbone()
        {
            return View();
        }

        //
        // GET: /Questionnaire/Details/5

        public ActionResult Details(int id = 0)
        {
            Questionnaire questionnaire = db.Questionnaires
                                            .Include(x => x.Questions)
                                            .SingleOrDefault(x => x.Id == id);
            if (questionnaire == null)
            {
                return HttpNotFound();
            }
            return View(questionnaire);
        }

        //
        // GET: /Questionnaire/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Questionnaire/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Questionnaire questionnaire)
        {
            if (ModelState.IsValid)
            {
                db.Questionnaires.Add(questionnaire);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(questionnaire);
        }

        //
        // GET: /Questionnaire/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Questionnaire questionnaire = db.Questionnaires.Find(id);
            if (questionnaire == null)
            {
                return HttpNotFound();
            }
            return View(questionnaire);
        }

        //
        // POST: /Questionnaire/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Questionnaire questionnaire)
        {
            if (ModelState.IsValid)
            {
                db.Entry(questionnaire).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(questionnaire);
        }

        //
        // GET: /Questionnaire/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Questionnaire questionnaire = db.Questionnaires.Find(id);
            if (questionnaire == null)
            {
                return HttpNotFound();
            }
            return View(questionnaire);
        }

        //
        // POST: /Questionnaire/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Questionnaire questionnaire = db.Questionnaires.Find(id);
            db.Questionnaires.Remove(questionnaire);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Questionnaire/Answer/5

        public ActionResult Answer(int id = 0)
        {
            var questionnaire = db.Questionnaires
                                  .Include("Questions")
                                  .Include("Questions.Choices")
                                  .SingleOrDefault();
            return View(questionnaire);
        }

        //
        // POST: /Questionnaire/Answer/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Answer(Questionnaire questionnaire)
        {
            var sessionId = Session.SessionID;
            foreach (var question in questionnaire.Questions)
            {
                db.Answers.Add(new Answer
                    {
                        SessionId = sessionId,
                        QuestionId = question.Id,
                        ChoiceId = question.Choices.First().Id
                    });
            }
            db.SaveChanges();
            TempData["Message"] = string.Format("Thank you for answering {0}",
                                                db.Questionnaires.Find(questionnaire.Id).Title);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Questionnaires.Web/Views/Questionnaire/Answer.cshtml
@using Questionnaires.Web.Models
@model Questionnaire

@{
    ViewBag.Title = "Questionnaire";
}

<h2>@Html.DisplayFor(x => Model.Title)</h2>

@if (Model.Questions.Any())
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <ol>
            @for (var i = 0; i < Model.Questions.Count; i++)
            {
                if (Model.Questions[i].Choices.Any())
                {
                    <li>
                        @Html.HiddenFor(x => x.Questions[i].Id)
                        @Html.DisplayFor(x => x.Questions[i].Text)
                        <ul>
                            @for (var j = 0; j < Model.Questions[i].Choices.Count; j++)
                            {
                                <li>
                                    @Html.RadioButtonFor(x => x.Questions[i].Choices[0].Id, Model.Questions[i].Choices[j].Id)
                                    @Html.DisplayFor(x => x.Questions[i].Choices[j].Text)
                                </li>
                            }         
                        </ul>
                    </li>
                }
            }
        </ol>
        <p>
            <input type="submit" value="Submit" />
        </p>
    }
}

Questionnaires.Web/Views/Questionnaire/Create.cshtml
@model Questionnaires.Web.Models.Questionnaire

@{
    ViewBag.Title = "Create";
}

<h2>Create Questionnaire</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="editor-label">
        @Html.LabelFor(model => model.Title)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
    </div>

    <p>
        <input type="submit" value="Create" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Questionnaires.Web/Views/Questionnaire/Delete.cshtml
@model Questionnaires.Web.Models.Questionnaire

@{
    ViewBag.Title = "Delete";
}

<h2>Delete @Html.DisplayFor(model => model.Title)</h2>

<h3>Are you sure you want to delete this?</h3>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Questionnaires.Web/Views/Questionnaire/Details.cshtml
@model Questionnaires.Web.Models.Questionnaire

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Title)</h2>

@if (Model.Questions.Any())
{
    <table>
        @foreach (var item in Model.Questions)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => item.Text)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Question", new {item.Id}, null) |
                    @Html.ActionLink("Details", "Details", "Question", new {item.Id}, null) |
                    @Html.ActionLink("Delete", "Delete", "Question", new {item.Id}, null)
                </td>
            </tr>
        }
    </table>    
}

<p>
    @Html.ActionLink("Create Question", "Create", "Question", new {questionnaireId = Model.Id}, null) |
    @Html.ActionLink("Edit", "Edit", new {Model.Id}) |
    @Html.ActionLink("Back to List", "Index")
</p>

Questionnaires.Web/Views/Questionnaire/Edit.cshtml
@model Questionnaires.Web.Models.Questionnaire

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Questionnaire</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.Id)

    <div class="editor-label">
        @Html.LabelFor(model => model.Title)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
    </div>

    <p>
        <input type="submit" value="Save" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Questionnaires.Web/Views/Questionnaire/Index.cshtml
@using Questionnaires.Web.Models
@model IEnumerable<Questionnaire>

@{
    ViewBag.Title = "Index";
}

<h2>Questionnaires</h2>

@if (TempData.ContainsKey("Message"))
{
    <h3 class="message">@TempData["Message"]</h3>
}
@if (Model.Any())
{
    <table>
        @foreach (Questionnaire item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.ActionLink("Answer", "Answer", new {item.Id}) |
                    @Html.ActionLink("Edit", "Edit", new {item.Id}) |
                    @Html.ActionLink("Details", "Details", new {item.Id}) |
                    @Html.ActionLink("Delete", "Delete", new {item.Id})
                </td>
            </tr>
        }
    </table>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>